Landing page and some stuff
Aitia-IIOT/ah5-docs-java-spring pull request #3
Opened 2024-10-21 17:05 UTC by borditamas

Mivel a Github Pages tud html-t is kezelni, gondoltam a landing page legyen kicsit jóképűbb :)

![image](https://github.com/user-attachments/assets/ad236aaa-735a-4ced-936c-d089527bf64c)

2024-10-21 17:27 UTC, Katinka666 approved these changes

2024-10-24 07:58 UTC, rbocsi commented on docs/articles/contribute.md
> +Technically it means that contributors have to have an [Eclipse Fundation Account](https://accounts.eclipse.org/user/register?destination=user/edit) with which the signed ECA is possible to submit! G
have to have => need

2024-10-24 08:06 UTC, rbocsi commented on docs/articles/contribute.md
> +The existance of the signed ECA is verified based on the authors commits. Your local Git client should hold and push the committs with the same email address like the Eclipse Foundation Account was c
existance => existence

2024-10-24 09:58 UTC, rbocsi commented on docs/index.html
> +				<div class="sys-group-list-item"><p>QoS Manager</p></div>
This not the name of the support system. I don't remember the exact name but it was something like this: Default QoS Evaluator

2024-10-24 09:59 UTC, rbocsi commented on docs/articles/tutorials.md
> +### [How to registery a system?]()
registery -> register

2024-10-24 09:59 UTC, rbocsi requested changes
see inline comments

2024-10-25 10:59 UTC, rbocsi approved these changes

2024-10-25 11:51 UTC, merged