Rb/service discovery sd
Aitia-IIOT/ah5-docs-java-spring pull request #7
Opened 2024-10-29 15:10 UTC by rbocsi

2024-10-31 21:56 UTC, Katinka666 requested changes

2024-10-31 21:56 UTC, Katinka666 commented on src/serviceregistry/5_0_0/sd/service-discovery/service-discovery_sd.tex
> +alivesAt & \pref{DateTime} & no & Request is looking for service ins\-tances that will be available at the specified moment of the future. \\ \hline
"Request" -> "Request**er**"

2024-10-31 21:56 UTC, Katinka666 commented on src/serviceregistry/5_0_0/sd/service-discovery/service-discovery_sd.tex
> +expiresAt & \pref{DateTime} & The moment of the future from which the service ins\-tance will not available. \\ \hline
"will not available" -> "will not **be** available"

2024-10-31 21:56 UTC, Katinka666 commented on src/serviceregistry/5_0_0/sd/service-discovery/service-discovery_sd.tex
> +\pdef{OperationStatus}  & Logical, textual or number value that indicates whether an operation is a success or a failure. It can be used multiple values for success and error cases to give additional
Same suggestion for "It can be used", but I might be wrong

2024-10-31 21:56 UTC, Katinka666 commented on src/serviceregistry/5_0_0/sd/service-discovery/service-discovery_sd.tex
> +\pdef{Version}          & Specifies a service instance version. Version must follows the Semantic Versioning. \\ \hline
"Version must follow**s**" -> "Version must follow"

2024-11-05 12:24 UTC, Katinka666 approved these changes

2024-11-08 11:12 UTC, borditamas approved these changes

2024-11-08 12:09 UTC, merged